# Schema for the configuration files of the Entity Access By Field.

entity_access_by_field.settings:
  type: config_object
  label: 'Entity Access by Field Settings'
  mapping:
    disable_public_visibility:
      type: boolean
      label: 'Disable public visibility'
    default_visibility:
      type: string
      label: 'The default visibility for fields'
field.storage_settings.entity_access_field:
  type: mapping
  label: 'Entity access field settings'
  mapping:
    allowed_values:
      type: sequence
      label: 'Allowed values list'
      sequence:
        type: mapping
        label: 'Allowed value with label'
        mapping:
          value:
            type: string
            label: 'Value'
          label:
            type: label
            label: 'Label'
    allowed_values_function:
      type: string
      label: 'Allowed values function'

field.field_settings.entity_access_field:
  label: 'Entity access field settings'
  type: mapping

field.value.entity_access_field:
  type: mapping
  label: 'Default value'
  mapping:
    value:
      type: string
      label: 'Value'
